/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#40474f',
        outline: '#707881',
        'outline-variant': '#c0c7d1',
        primary: '#00507d',
        'primary-container': '#0369a1',
        'on-primary': '#ffffff',
        secondary: '#006591',
        'secondary-container': '#39b8fd',
        'secondary-fixed': '#c9e6ff',
        'secondary-fixed-dim': '#89ceff',
        'on-secondary-container': '#004666',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-variant': '#dae2fd',
        hro: {
          blue: '#0369a1',
          celeste: '#0ea5e9',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600', letterSpacing: '-0.015em' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'title-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'title-sm': ['13px', { lineHeight: '18px', fontWeight: '600' }],
        'body-lg': ['15px', { lineHeight: '22px' }],
        'body-md': ['13px', { lineHeight: '18px' }],
        'body-sm': ['12px', { lineHeight: '16px' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.02em' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600', letterSpacing: '0.03em' }],
        'metric-display': ['32px', { lineHeight: '36px', fontWeight: '700', letterSpacing: '-0.03em' }],
        'metric-sub': ['20px', { lineHeight: '24px', fontWeight: '700', letterSpacing: '-0.02em' }],
      },
      boxShadow: {
        card: '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
        popover: '0 4px 6px -1px rgba(15, 23, 42, 0.08), 0 2px 4px -2px rgba(15, 23, 42, 0.04)',
        modal: '0 20px 25px -5px rgba(15, 23, 42, 0.16), 0 8px 10px -6px rgba(15, 23, 42, 0.08)',
        dock: '0 -4px 16px rgba(0, 0, 0, 0.06)',
      },
    },
  },
  plugins: [],
}
