/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: 'rgb(var(--hro-surface) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--hro-surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--hro-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--hro-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--hro-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--hro-surface-container-highest) / <alpha-value>)',
        'on-surface': 'rgb(var(--hro-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--hro-on-surface-variant) / <alpha-value>)',
        outline: 'rgb(var(--hro-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--hro-outline-variant) / <alpha-value>)',
        primary: 'rgb(var(--hro-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--hro-primary-container) / <alpha-value>)',
        'on-primary': 'rgb(var(--hro-on-primary) / <alpha-value>)',
        secondary: 'rgb(var(--hro-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--hro-secondary-container) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--hro-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--hro-secondary-fixed-dim) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--hro-on-secondary-container) / <alpha-value>)',
        error: 'rgb(var(--hro-error) / <alpha-value>)',
        'on-error': 'rgb(var(--hro-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--hro-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--hro-on-error-container) / <alpha-value>)',
        'surface-variant': 'rgb(var(--hro-surface-variant) / <alpha-value>)',
        hro: {
          blue: '#0369a1',
          celeste: '#0ea5e9',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600', letterSpacing: '-0.015em' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'title-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'title-sm': ['13px', { lineHeight: '18px', fontWeight: '600' }],
        'body-lg': ['15px', { lineHeight: '22px' }],
        'body-md': ['13px', { lineHeight: '18px' }],
        'body-sm': ['12px', { lineHeight: '16px' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.02em' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600', letterSpacing: '0.03em' }],
        'metric-display': ['32px', { lineHeight: '36px', fontWeight: '700', letterSpacing: '-0.03em' }],
        'metric-sub': ['20px', { lineHeight: '24px', fontWeight: '700', letterSpacing: '-0.02em' }],
      },
      boxShadow: {
        card: '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
        popover: '0 4px 6px -1px rgba(15, 23, 42, 0.08), 0 2px 4px -2px rgba(15, 23, 42, 0.04)',
        modal: '0 20px 25px -5px rgba(15, 23, 42, 0.16), 0 8px 10px -6px rgba(15, 23, 42, 0.08)',
        dock: '0 -4px 16px rgba(0, 0, 0, 0.06)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.375rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
      },
    },
  },
  plugins: [],
}
